name: Publish

on:
  release:
    types: [created]

permissions: write-all

jobs:
  compile:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12] #, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Lint
        run: deno task lint

      - name: Compile SQLite Binary
        run: deno task compile

      - name: Test
        run: deno task test

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: binaries/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "This is my release text"

      - name: Upload Binary
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TODO what are we actually uploading
        # with:
        #   args: 'example-*'
